# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3f15e5bfbaa923525b608374e57dccc91ef07086f5959231eb834242b1e1cc80d759724e7d2cc90e7799af2682c39b47fa74c7b624b303faff00e8813dabd0

test:
  secret_key_base: e8011b03412b0592d46a3d2721e999c7d1af6b65d231437d21bad51a79de3815a4c0b66ffce3ccc4bd76091b2b6841313d344186257c5adb3cbb8c56265e2977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
